version: '3'
services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    command: 
      - bash
      - -c
      - "uwsgi -i /home/api_server/kakao_chatbot/uwsgi.ini && tail -f /dev/null"
    ports: 
      - "8000:8000"
    expose:
      - "8000"

